@startuml
skinparam actorStyle awesome
actor "사용자" as user

package "스마트홈 전기관리 시스템" {
  package "클라우드 플랫폼" {
    boundary "UserInterface" as UI
    control "DeviceControlController" as CloudDCC
  }

  package "홈 게이트웨이" {
    control "GatewayController" as GatewayCtrl
    "application logic" "ProtocolAdapter" as PA
    "application logic" "CommandExecutor" as CE
    boundary "DeviceInterface" as DI
  }
}

user -> UI: 1. 기기 제어 요청(deviceID, command)
UI -> CloudDCC: 1.1. 제어 명령 전달(userID, deviceID, command)
CloudDCC -> GatewayCtrl: 1.2. 원격 제어 명령 전송(deviceID, command)
GatewayCtrl -> PA: 1.3. 프로토콜 변환(command)
PA --> GatewayCtrl: protocolCmd
GatewayCtrl -> CE: 1.4. 명령 실행(protocolCmd)
CE -> DI: 1.5. 기기 제어(protocolCmd)
DI --> CE: result
CE --> GatewayCtrl: result
GatewayCtrl --> CloudDCC: newStatus
CloudDCC -> UI: 1.6. 변경 결과 전달(newStatus)
UI -> user: 1.7. 화면 업데이트()
@enduml